# Generated by Django 3.2.25 on 2024-12-13 01:46

import AppDesign.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorDesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заявки')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваш email')),
                ('phone', models.CharField(max_length=15, verbose_name='Ваш телефон')),
                ('project_description', models.TextField(verbose_name='Описание заявки')),
                ('design_image', models.ImageField(upload_to='design_images/', validators=[AppDesign.models.validate_image], verbose_name='Фото помещения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Новая', 'Новая'), ('В процессе', 'В процессе'), ('Завершена', 'Завершена')], default='Новая', max_length=20, verbose_name='Статус')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочность')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppDesign.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
